// Products courses table
let productsCourses = [
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV274",
      productName: "Túi Tode vải jeans co giãn đa chiều",
      userID: "#US.AGV223",
      price: "400.000",
      sku: "TB.001.AGF436SJGA",
      createdDate: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV276",
      productName: "Balo leo núi chất lượng cao",
      userID: "#US.AGV267",
      price: "450.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    },
    {
      productID: "#PD.AGV277",
      productName: "Áo khoác chống nắng",
      userID: "#US.AGV294",
      price: "300.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Active",
      class: "active",
    },
    {
      productID: "#PD.AGV279",
      productName: "Giày thể thao",
      userID: "#US.AGV274",
      price: "800.000",
      sku: "TB.001.AGF436SJGA",
      joinedTime: "01/01/2024",
      status: "Inactive",
      class: "inactive",
    }
  ]
  

// Products courses table
const _tbodyProducts = $("tbody.products");
const productsList = productsCourses.map(function (item) {
  _tbodyProducts.append(
    `
      <tr>
          <td class="fw-bold">
            <a href="./ambOrderProductsDetail.html" class="text-dark">
              ${item.productID}
            </a>
          </td>
          <td>
            <a href="./ambOrderProductsDetail.html" class="text-dark">
              ${item.productName}
            </a>
          </td>
          <td class="fw-bold">
            <a href="./ambOrderProductsDetail.html" class="text-dark">
              ${item.userID}
            </a>
          </td>
          <td>
            <a href="./ambOrderProductsDetail.html" class="text-dark">
              <b>${item.price}</b>đ
            </a>
          </td>
          <td>
            <a href="./ambOrderProductsDetail.html" class="text-dark">
              ${item.sku}
            </a>
          </td>
          <td>
            <a href="./ambOrderProductsDetail.html" class="text-dark">
              ${item.createdDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderProductsDetail.html"  class="${item.class}">
              ${item.status}
            </a>
          </td>
      </tr>`
  );
});