// Orders courses table
let ordersCourses = [
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000", 
      createdDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      orderID: "#OR.AGV274",
      userID: "#US.AGV223",
      orderType: "Delivery",
      catalogID: "#CA.AGV274",
      referralID: "5",
      shippingFee: "30.000",
      subTotal: "784.000",
      createdDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    }
  ]
  

// Orders courses table
const _tbodyOrders = $("tbody.orders");
const ordersList = ordersCourses.map(function (item) {
  _tbodyOrders.append(
    `
      <tr>
          <td class="fw-bold">
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              ${item.orderID}
            </a>
          </td>
          <td class="fw-bold">
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              ${item.userID}
            </a>
          </td>
          <td>
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              ${item.orderType}
            </a>
          </td>
          <td class="fw-bold">
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              ${item.catalogID}
            </a>
          </td>
          <td class="referralID">
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              ${item.referralID}
            </a>
          </td>
          <td>
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              <b>${item.shippingFee}</b>đ
            </a>
          </td>
          <td>
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              <b>${item.subTotal}</b>đ
            </a>
          </td>
          <td>
            <a href="./ambOrderOrdersDetail.html" class="text-dark">
              ${item.createdDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderOrdersDetail.html"  class="${item.class}">
              ${item.status}
            </a>
          </td>
      </tr>`
  );
});