// Users courses table
let usersCourses = [
    {
      userID: "#US.AGV100",
      phoneNumber: "0001230000",
      storeName: "MiniStop",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "13",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "045613300",
      storeName: "MiniStop",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "13",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000123515",
      storeName: "MiniStop",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "13",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0123141000",
      storeName: "MiniStop",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "13",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "MiniStop",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "13",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "12",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "12",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "12",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "GS25",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "12",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "GS25",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "12",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "GS25",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "22",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "GS25",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "22",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV100",
      phoneNumber: "0000000000",
      storeName: "GS25",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "22",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "GS25",
      type: "Free22",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "22",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "22",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "22",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free33",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "000001231",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "1231231231",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "1231231231",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV300",
      phoneNumber: "09123",
      storeName: "khoa",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "14",
      catalogs: "5",
      status: "Blocked",
      class: "blocked",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Active",
      class: "active",
    },
    {
      userID: "#US.AGV274",
      phoneNumber: "0000000000",
      storeName: "Circle K",
      type: "Free",
      publishTime: "NULL",
      joinedTime: "01/01/2024",
      sponsoredDate: "NULL",
      products: "17",
      catalogs: "4",
      status: "Blocked",
      class: "blocked",
    },
  ];

// Users courses table
const _tbodyUsers = $("tbody.users");
const result7 = usersCourses.map(function (item) {
  _tbodyUsers.append(
    `
      <tr>
          <td class="fw-bold">
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.userID}
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              +84 <b>${item.phoneNumber}</b>
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.storeName}
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.type}
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.publishTime}
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.joinedTime}
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.sponsoredDate}
            </a>
          </td>
          <td class="products">
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.products}
            </a>
          </td>
          <td class="catalogs">
            <a href="./ambOrderUsersDetail.html" class="text-dark">
              ${item.catalogs}
            </a>
          </td>
          <td>
            <a href="./ambOrderUsersDetail.html"  class="${item.class}">
              ${item.status}
            </a>
          </td>
      </tr>`
  );
});