// Alerts courses table
let alertsCourses = [
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour... ",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    notificationID: "#NO.AGV274",
    notificationTitle: "Summer Sale 50% to All member on the Ha Long Bay start ship tour...",
    type: "Promotion",
    linkTo: "URL",
    loop: "Yes",
    createdDate: "16/10/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
];

// Alerts courses table
const _tbodyAlerts = $("tbody.alerts");
const alertsList = alertsCourses.map(function (item) {
  _tbodyAlerts.append(
    `
      <tr>
          <td class="fw-bold">
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.notificationID}
            </a>
          </td>
          <td>
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.notificationTitle}
            </a>
          </td>
          <td>
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.type}
            </a>
          </td>
          <td class="link">
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.linkTo}
            </a>
          </td>
          <td>
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.loop}
            </a>
          </td>
          <td>
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.createdDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderAlertsDetail.html" class="text-dark">
              ${item.startDate} - ${item.endDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderAlertsDetail.html"  class="${item.class}">
              ${item.status}
            </a>
          </td>
      </tr>`
  );
});

let profilePic = document.getElementById("profile-pic");
let inputFile = document.getElementById("upload");

inputFile.onchange = function () {
  profilePic.src = URL.createObjectURL(inputFile.files[0]);
  document.querySelector(".upload-label").style.display = "none";
  document.querySelector(".btn-change").classList.remove("non-active");
  document.querySelector(".btn-change").classList.add("active");
};


