// Popups courses table
let popupsCourses = [
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Scheduled",
    class: "scheduled",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Open",
    class: "open",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Completed",
    class: "completed",
  },
  {
    popupID: "#PU.AGV274",
    popupTitle: "Beginner - Download Sample Catalogs",
    index: "1",
    type: "Sample Download",
    linkTo: "Amoeba Share",
    createdDate: "01/08/2024",
    startDate: "08/08/2024",
    endDate: "08/09/2024",
    status: "Canceled",
    class: "canceled",
  },
];

// Products courses table
const _tbodyPopups = $("tbody.popups");
const popupsList = popupsCourses.map(function (item) {
  _tbodyPopups.append(
    `
      <tr>
          <td class="fw-bold">
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.popupID}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.popupTitle}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.index}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.type}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.linkTo}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.createdDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html" class="text-dark">
              ${item.startDate} - ${item.endDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderPopupsDetail.html"  class="${item.class}">
              ${item.status}
            </a>
          </td>
      </tr>`
  );
});

let profilePic = document.getElementById("profile-pic");
let inputFile = document.getElementById("upload-popups");

inputFile.onchange = function () {
  profilePic.src = URL.createObjectURL(inputFile.files[0]);
  document.querySelector(".upload-popups-label").style.display = "none";
  document.querySelector(".btn-change").classList.remove("non-active");
  document.querySelector(".btn-change").classList.add("active");
};


