// Reports courses table
let reportsCourses = [
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "New",
      class: "new",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Processing",
      class: "processing",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Delivering",
      class: "delivering",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Pick-up Waiting",
      class: "pick-upWaiting",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Completed",
      class: "completed",
    },
    {
      reportID: "#OR.AGV274",
      catalogID: "#CA.AGV274",
      userID: "#US.AGV274",
      reportQuantity: "28",
      reason: "Reason list",
      latestDate: "01/01/2024",
      status: "Canceled",
      class: "canceled",
    }
]

// Reports courses table
const _tbodyReports = $("tbody.reports");
const reportsList = reportsCourses.map(function (item) {
  _tbodyReports.append(
    `
      <tr>
          <td class="fw-bold">
            <a href="./ambOrderReportsDetail.html" class="text-dark">
              ${item.reportID}
            </a>
          </td>
          <td>
            <a href="./ambOrderReportsDetail.html" class="text-dark">
              ${item.catalogID}
            </a>
          </td>
          <td>
            <a href="./ambOrderReportsDetail.html" class="text-dark">
              ${item.userID}
            </a>
          </td>
          <td>
            <a href="./ambOrderReportsDetail.html" class="text-dark">
              ${item.reportQuantity}
            </a>
          </td>
          <td class="link">
            <a href="./ambOrderReportsDetail.html" class="text-dark">
              ${item.reason}
            </a>
          </td>
          <td>
            <a href="./ambOrderReportsDetail.html" class="text-dark">
              ${item.latestDate}
            </a>
          </td>
          <td>
            <a href="./ambOrderReportsDetail.html"  class="${item.class}">
              ${item.status}
            </a>
          </td>
      </tr>`
  );
});